### PR TITLE
cannot read path of null if `idType : String` is used in plugin…

### PR DESCRIPTION
**Pull request by efstathiosntonas**

### CODE REVIEW

**Comment by vikpe** [comment]
@efstathiosntonas thanks for the PR. 

Could you provide an example code snippet on how to reproduce the error? Also, the tests needs to be updated as they break with the suggested changes.

**Comment by efstathiosntonas** [comment]
The scenario is simple, if in plugin settings you use `idType: String` in a `Category` schema instead of `Scema.ObjectId` and you try to create a new category via a post request with the following data (parent key is empty string) provided below then you get the error I described in title.

example post data:

```
{
  title: "test",
  parent: ""
}

```

If you need further info please let me know. Great library btw, thanks.

**Comment by vikpe** [comment]
Ok, I'll look into it.

**Comment by vikpe** [comment]
Have you set the id type in _both_ the schema and plugin options?

E.g:
```javascript
const MySchema = new mongoose.Schema({
  _id: {type: String},
  name: String,
});

MySchema.plugin(MpathPlugin, {idType: String});
```

I wrote a test (see https://github.com/vikpe/mongoose-mpath/commit/9ac9932ae6df339e1e26ee0fad7264b7f78f44cd) to confirm that it does work to use empty `parent` when using string as id type.

However, if I don't set the id type in both definitions I get a cast error:
`LocationWithStringAsIdType validation failed: _id: Cast to ObjectID failed for value "wo" at path "_id"`.

**Comment by vikpe** [comment]
You shouldn't set `parent` in your schema definition. It's added by the plugin itself:

https://github.com/vikpe/mongoose-mpath/blob/9ac9932ae6df339e1e26ee0fad7264b7f78f44cd/lib/mpath.js#L22-L28

**Comment by efstathiosntonas** [comment]
Oh, didn’t see that, I went straight to the `null` bug when inspecting source. 

Discard this pr, it’s unnecessary now. I believe readme should be updated (to avoid such confusions) with schema example.Thanks vipke keep up the good work!

**Comment by vikpe** [comment]
Yes will do!

**Pull request closed without merging**
