### PR TITLE
Refactored lib to use promises and mongoose 5.3

### PR DESCRIPTION
**Pull request by florianbepunkt**
This is probably a breaking change, so I upped semver. I added some convenience stuff to the dev dependencies like linting and @babel/polyfill

There are a few things to discuss/left to do:

- Is it okay for you that lib code uses es6 features. Right now it is scoped variables and arrow functions. So it could be backported
- since it no longer uses callbacks we have an issue in getChildrenTree method, since param handling is based on wether a callback method was passed as an argument. This no longer works. So either (a) you have to explicitly pass null as rootDoc, (b) switch order of args and rootDoc or (c) make rootDoc a property of args. I would favor the latter
- I had automatic prettier lint enabled in editor. so sorry for the amount of lines changed
- Updates for docs would be necessary once the previously mentioned points are resolved

### CODE REVIEW

**Comment by vikpe** [comment]
@florianbepunkt Nice stuff!

I've added a copy of the existing code to a support branch (`support/1.x`) in order to prepare for major version bump with breaking changes.

1. Let's go for ES6, it's soon 2019 :smile: 
2. Sure, go for `c)`.
3. No problems, can use whatever lint settings.

**Comment by florianbepunkt** [comment]
@vikpe Thank you for the review. I will complete this later this week and update the PR.

**Comment by vikpe** [comment]
No hurries, I'll be away Wednesday to Sunday.

**Comment by florianbepunkt** [comment]
@vikpe completed the pr. not sure why codeclimate is failing. length of methods/files have not changed significantly with these commits.

**Pull request merged**
